services:
  - type: web
    name: specific-sequence-finder
    env: python
    plan: starter  # 或 standard
    buildCommand: |
      # 安装 Miniconda
      curl -fsSLo ~/miniconda.sh https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
      bash ~/miniconda.sh -b -p $HOME/miniconda
      export PATH="$HOME/miniconda/bin:$PATH"

      # 创建并激活环境，安装 Bioconda 的 BLAST
      conda install -y -c bioconda blast
      pip install -r requirements.txt

    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0


