services:
  - type: web
    name: specific-sequence-finder
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0

