services:
  - type: web
    name: specific-sequence-finder
    env: python
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y ncbi-blast+ &&
      pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0
